//Server actions

export default {
	server: {
		SEND_MESSAGE:  "server/SEND_MESSAGE",
		RECEIVE_MESSAGE: "server/RECEIVE_MESSAGE",
		AUTHENTICATE_USER: "server/AUTHENTICATE_USER",
		CREATE_USER: "server/CREATE_USER",
		ADD_SUBSCRIPTION: "server/ADD_SUBSCRIPTION",
		GET_MESSAGES: "server/GET_MESSAGES"
	},
	message: {
		RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
		UPDATE_NEW_MESSAGE_VALUE: "UPDATE_NEW_MESSAGE_VALUE",
		LATEST_MESSAGES: "LATEST_MESSAGES",
		UPDATE_DEST: "UPDATE_DEST",
		NEW_DEST: "NEW_DEST",
		SENDING_MESSAGE: "SENDING_MESSAGE"
	},
	application: {
		TOGGLE_SIDEMENU: "TOGGLE_SIDEMENU",
		SET_CHANNELJOINDIALOG: "SET_CHANNELJOINDIALOG"
	},
	user:{
		SET_USER: "SET_USER",
		CREATE_NEW_USER: "CREATE_NEW_USER",
		SET_AUTH_EMAIL: "SET_AUTH_EMAIL",
		UPDATE_NEW_USERNAME_VALUE: "UPDATE_NEW_USERNAME_VALUE",
		NOT_AUTH: "NOT_AUTH",
		INIT_LOGIN: "INIT_LOGIN"
	},
	map:{
		FETCH_POSITION_FETCHING: "FETCH_POSITION_FETCHING",
		FETCH_POSITION_FULFILLED: "FETCH_POSITION_FULFILLED",
		FETCH_POSITION_ERROR: "FETCH_POSITION_ERROR"
	}
}