//Server actions

export default {
	server: {
		SEND_MESSAGE:  "server/SEND_MESSAGE",
		RECEIVE_MESSAGE: "server/RECEIVE_MESSAGE",
		AUTHENTICATE_USER: "server/AUTHENTICATE_USER",
		CREATE_USER: "server/CREATE_USER"
	},
	message: {
		RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
		UPDATE_NEW_MESSAGE_VALUE: "UPDATE_NEW_MESSAGE_VALUE"
	},
	application: {
		SET_SIDEMENU: "SET_SIDEMENU"
	},
	user:{
		SET_USER: "SET_USER",
		CREATE_NEW_USER: "CREATE_NEW_USER",
		SET_AUTH_EMAIL: "SET_AUTH_EMAIL",
		UPDATE_NEW_USERNAME_VALUE: "UPDATE_NEW_USERNAME_VALUE"
	}
}