//Server actions

export default {
	server: {
		SEND_MESSAGE:  "server/SEND_MESSAGE",
		RECEIVE_MESSAGE: "server/RECEIVE_MESSAGE",
		AUTHENTICATE_USER: "server/AUTHENTICATE_USER",
		CREATE_USER: "server/CREATE_USER",
		ADD_SUBSCRIPTION: "server/ADD_SUBSCRIPTION",
		GET_MESSAGES: "server/GET_MESSAGES"
	},
	message: {
		RECEIVE_MESSAGE: "RECEIVE_MESSAGE",
		UPDATE_NEW_MESSAGE_VALUE: "UPDATE_NEW_MESSAGE_VALUE",
		LATEST_MESSAGES: "LATEST_MESSAGES",
		UPDATE_DEST: "UPDATE_DEST"
	},
	application: {
		SET_SIDEMENU: "SET_SIDEMENU"
	},
	user:{
		SET_USER: "SET_USER",
		CREATE_NEW_USER: "CREATE_NEW_USER",
		SET_AUTH_EMAIL: "SET_AUTH_EMAIL",
		UPDATE_NEW_USERNAME_VALUE: "UPDATE_NEW_USERNAME_VALUE",
		NOT_AUTH: "NOT_AUTH"

	}
}